version: '3.8'
services:
  mysql:
    image: mysql:5.7.44
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306

volumes:
  mysql: